# Overrides the docker-compose file for production environment
# - Adds nginx with basic auth in front of the app
# - Production env file for the app

version: '3'

volumes:
  nginx:

services:

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.nims.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
